// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountPrimingRunSummary } from "./AccountPrimingRunSummary";

export type AccountPrimingStatus = { running: boolean, intervalSeconds: number | null, startedAt: bigint | null, currentRunStartedAt: bigint | null, currentProfileName: string | null, lastRun: AccountPrimingRunSummary | null, };
