// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { AccountPrimingProfileOutcome } from "./AccountPrimingProfileOutcome";
import type { RateLimitSnapshot } from "./RateLimitSnapshot";

export type AccountPrimingProfileResult = { profileName: string, account: Account | null, outcome: AccountPrimingProfileOutcome, beforeRateLimits: RateLimitSnapshot | null, afterRateLimits: RateLimitSnapshot | null, error: string | null, };
