// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountPrimingProfileResult } from "./AccountPrimingProfileResult";

export type AccountPrimingRunSummary = { startedAt: bigint, completedAt: bigint, cancelled: boolean, primedCount: number, alreadyActiveCount: number, unsupportedCount: number, failedCount: number, results: Array<AccountPrimingProfileResult>, };
