// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { RateLimitSnapshot } from "./RateLimitSnapshot";

export type AuthProfileSummary = { name: string, account: Account | null, rateLimits: RateLimitSnapshot | null, active: boolean, };
